name: Weekly Website Screenshots

on:
  schedule:
    # Run at 00:00 UTC every Sunday
    - cron: '0 0 * * 0'

  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        type: string

jobs:
  generate-screenshots:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Generate Screenshots
      run: python main.py
    
    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update weekly screenshots" || exit 0
        git push
